classDiagram
    direction LR
    class Ruangan {
      <<interface>>
      +salin() Ruangan
    }
    class RuanganDasar
    class DekoratorRuangan
    Ruangan <|.. RuanganDasar
    Ruangan <|.. DekoratorRuangan
    RuanganDasar ..> Ruangan : clone
    DekoratorRuangan ..> Ruangan : clone
